### ISSUE TITLE
support for fluentd's in_http plugin

### ISSUE THREAD

**Issue by Globegitter** [fluent-plugins-nursery/fluent-plugin-out-http#20]
It would be great if this plugin could support http://docs.fluentd.org/v0.12/articles/in_http plugin. I know it seems like a bit of an odd request, but I have two fluentd nodes that are connecting over the internet. And one is sitting behind an nginx proxy that is securing the access via basic auth, hence I am using your plugin. And if there was  a way to define e.g. `endpoint_url https://address.com/:tag` or something, that it then dynamically creates the URL that would be great.

**Comment by cosmo0920** [comment]
Since v1.0.1, which needs to use Fluentd v0.14 or later, we can send in_http with `${tag}` placeholder.

### out_http configuration:

```aconf
<source>
  @type forward
  port 24225
  bind 127.0.0.1
  @label @RAW
</source>
<label @RAW>
  <match **>
    @type http
    endpoint_url http://localhost:8888/${tag}/
    serializer json
    # needs to enable ${tag} placeholder
    buffered true 
    <buffer>
      flush_interval 1s
    </buffer>
  </match>
</label>
```

### in_http configuration

```aconf
<source>
  @type http
  port 8888
  bind 0.0.0.0
  body_size_limit 32m
  keepalive_timeout 10s
  @label @RAW
</source>
<label @RAW>
  <match **>
    @type stdout
  </match>
</label>
```

is this your expected feature?

**Comment by Globegitter** [comment]
That seems like it should do the trick. Thanks for the response!
