### ISSUE TITLE
Extra Headers would be useful

### ISSUE THREAD

**Issue by artheus** [fluent-plugins-nursery/fluent-plugin-out-http#24]
For logging to services where authentication tokens are sent using the HTTP Headers, it would be really useful to be able to add headers in the config of this plugin.

**Comment by rebeccacaroline** [comment]
➕

**Comment by rebeccacaroline** [comment]
@artheus did you find a workaround for this?

**Comment by artheus** [comment]
@rebeccacaroline No. I just looked through this project quickly and filed this issue in the hope of this getting done. I was never really blocked by this though. One workaround could be to setup a nginx proxy between which checks the source of the request and just adds the token. But that seems to be a bit far....

Looking at the code here: https://github.com/ento/fluent-plugin-out-http/blob/1da8b6b223f9c97a312ccc8b693465f49ebfc0d7/lib/fluent/plugin/out_http.rb#L88 shows me that there has been a thought of actually doing this, but it has not been done. I would suggest creating a pull-request for this. The plugin code seems simple enough.

**Comment by artheus** [comment]
Great work @cosmo0920! 👍🏻
