### ISSUE TITLE
Does any POST operation that doesn't get a 2XX response back trigger a retry if used with buffered-plugin?

### ISSUE THREAD

**Issue by komal-SkyNET** [fluent-plugins-nursery/fluent-plugin-out-http#42]
When do messages go into retry loop?

I have a POST operation that's done by the http-out plugin used in conjunction with buffered plugin. Does it retry delivering the message on a 400 response?

**Comment by cosmo0920** [comment]
No. Just output warnging message.
https://github.com/fluent-plugins-nursery/fluent-plugin-out-http/blob/master/lib/fluent/plugin/out_http.rb#L186-L193
Could you try to write a patch to fix this?

**Comment by komal-SkyNET** [comment]
Yep. I was looking at that earlier today. I'll submit a PR soon. Thanks.
