### ISSUE TITLE
Add support for combined events

### ISSUE THREAD

**Issue by adawalli** [fluent-plugins-nursery/fluent-plugin-out-http#47]
#### Problem
Currently - even when using buffering - events are sent out as individual POSTS/PUTS, etc. Would it be possible to combine events into single POSTS/PUTS? For example, when using JSON, you could put all events in a JSON array.

**Comment by cosmo0920** [comment]
Sorry for being late.

I think that JSON array is not enough representation for combined events.
Instead, I use `application/x-ndjson` representation for combined events in #50.
Could you try #50 ?

**Comment by cosmo0920** [comment]
#50 has been merged. Closing.
