### ISSUE TITLE
no patterns matched tag

### ISSUE THREAD

**Issue by alandtsang** [fluent-plugins-nursery/fluent-plugin-out-http#54]
#### Problem
Hi, I want to send `/var/log/containers/*.log` to my remote http server via http, but it doesn't seem to work.

```
kubectl logs -f -n kube-system fluentd-es-v2.6.0-lp5fw
```
There are many warning logs as follows:
```
2019-08-20 06:50:55 +0000 [warn]: no patterns matched tag="kubelet"
2019-08-20 06:52:34 +0000 [warn]: no patterns matched tag="kubernetes.var.log.containers.nginx-ingress-controller-68b4679fb5-rmsh2_ingress-nginx_nginx-ingress-controller-66d4bac29eb19fd33242bcd177dcb57cffcae3e0b7cf5fc77709b74e3f09c19b.log"
```

And my http server didn't receive any data
...

#### Steps to replicate
Provide example config and message

My fluentd configuration information is as follows:
```yaml
containers.input.conf: |-
  <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      tag raw.kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

output.conf: |-
    <match **>
      @type http
      endpoint_url http://10.2.208.184:9090/
      serializer json
      buffered true
    </match>
```

#### Expected Behavior or What you need to ask
My http server received the log sent by fluentd.
...

#### Using Fluentd and out_http plugin versions

* OS version
```
Linux Debian 4.19.28.bsk.3-amd64
```
* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
```
$ fluentd --version
fluentd 1.5.1
```
* out_http plugin 1.x.y or 0.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
```
$ fluent-gem list
fluent-plugin-out-http (1.3.1)
```
* Bear Metal or Within Docker or Kubernetes or others? (optional)

**Comment by cosmo0920** [comment]
Could you confirm Fluentd boot log?

And why do you use `output.conf` instead of `containers.output.conf` the following lines?

> ```
> output.conf: |-
>    <match **>
>     @type http
>      endpoint_url http://10.2.208.184:9090/
>      serializer json
>      buffered true
>    </match>
> ```

**Comment by alandtsang** [comment]
Thank you for your reply.

At first I wanted to collect all the containers' logs and send them to my log server via fluentd, and finally solved them with the fluent bit.

This issue can be closed, thanks again for the reply.
