### ISSUE TITLE
Monitoring of a file not working. Can't see the logs ingested

### ISSUE THREAD

**Issue by isha132** [fluent-plugins-nursery/fluent-plugin-out-http#67]
#### Problem
Hi,

I am new to fluentd and trying to figure out how to monitor a path and collect logs via fluentd and its not working. Could you please tell me what I am missing

Below is the code in use and I am not getting any error while restarting fluent daemon. I am trying to monitor aishtest.log file from the temp directory.

```aconf
<source>
 @type tail
 path /tmp/aishtest.log
 pos_file /tmp/pos_file_secure.log.pos
 tag "*.*"
 read_from_head true
 <parse>
  @type none
 </parse>
</source>
<filter *.*>
 @type parser
 key_name log
 reserve_data true
 remove_key_name_field true
 <parse>
  @type json
 </parse>
 emit_invalid_record_to_error false
</filter>
<match *>
  @type stdout
  @type kafka2
  brokers broker1 broker2
  ssl_ca_cert abc
  ssl_client_cert "/etc/fluent/certs/##"
  ssl_client_cert_key "/etc/fluent/certs/#"
  ssl_ca_certs_from_system false
  ssl_verify_hostname false
  client_id xyz
  use_event_time true
  <format>
    @type json
  </format>
  compression_codec gzip
  max_send_retries 1024
  required_acks -1
  sasl_over_ssl false
</match>
```

* OS version
* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
* out_http plugin 1.x.y or 0.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
* Bear Metal or Within Docker or Kubernetes or others? (optional)

**Comment by isha132** [comment]
`<source>
 @type tail
 path /tmp/aishtest.log
 pos_file /tmp/pos_file_secure.log.pos
 tag "*.*"
 read_from_head true
 <parse>
  @type none
 </parse>
</source>
<filter *.*>
 @type parser
 key_name log
 reserve_data true
 remove_key_name_field true
 <parse>
  @type json
 </parse>
 emit_invalid_record_to_error false
</filter>
<match *>
  @type stdout
  @type kafka2
  brokers broker1 broker2
  ssl_ca_cert abc
  ssl_client_cert "/etc/fluent/certs/##"
  ssl_client_cert_key "/etc/fluent/certs/#"
  ssl_ca_certs_from_system false
  ssl_verify_hostname false
  client_id xyz
  use_event_time true
  <format>
    @type json
  </format>
  compression_codec gzip
  max_send_retries 1024
  required_acks -1
  sasl_over_ssl false
</match>
`

**Comment by cosmo0920** [comment]
Here is fluent-plugin-out-http plugin repository not in_tail and filter_parser, and out_kafka2.
You should report your issue into appropriate repository.
Closing.
Anyway, thanks for using Fluentd: :punch:
